# Generated by Django 2.2.12 on 2022-07-20 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dev',
            name='description',
            field=models.TextField(max_length=250),
        ),
        migrations.AlterField(
            model_name='game',
            name='genre',
            field=models.CharField(choices=[('A', 'Action/Adventure'), ('R', 'RPG'), ('F', 'FPS'), ('3', '3D Platformer'), ('2', '2D Platformer'), ('P', 'Puzzle'), ('R', 'Rhythm'), ('S', 'Strategy'), ('O', 'Open World'), ('V', 'Visual Novel'), ('C', 'Competitive Fighting Game'), ('M', 'MOBA'), ('L', 'Life Sim'), ('I', 'Immersive Sim')], default='A', max_length=1),
        ),
        migrations.AlterField(
            model_name='game',
            name='release',
            field=models.PositiveIntegerField(default=1970),
        ),
    ]
